### PR TITLE
V1.1.0 container update

### PR DESCRIPTION
**Pull request by jasonb5**
## Description
This PR will be a general update for containers.
- Add runtime configuration for frontend
- Automate container build/release to ghcr.io

Todo before merge:
- [ ] Add test
- [ ] Fix container workflow trigger
- [ ] Revert 36b779cec9277b69cb2f45a663449b94f3e63581

Fixes # (issue)

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

- [ ] Local Pre-commit Checks
- [ ] CI/CD Build

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] If applicable - I have commented my code, particularly in hard-to-understand areas
- [ ] If applicable - I have made corresponding changes to the documentation
- [ ] If applicable - I have added tests that prove my fix is effective or that my feature works
- [ ] If applicable - New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jasonb5** [comment]
Here's a status of all commits made in https://github.com/esgf2-us/metagrid/pull/594.
- 6bc19e8 - Applied
- 5c3b12c - Applied
- 09ed0fb - Skipped
- 7bd6060 - Skipped
- 5dd6946 - Applied
- 9c19305 - Applied
- eba2321 - Applied
- 4efb770 - Applied
- 44206ac - Applied
- 3a0d9df - Skipped
- 9ec492b - Skipped
- ac73d55 - Applied
- a3eaf7a - Skipped
- 36b779c - Applied
- 9762034 - Applied

**Comment by sashakames** [comment]
Thank you @jasonb5 @downiec could review just to be sure, and I'll do a production regression test merge on our green-net server.  Have you run this branch on Nimbus yet?

**Comment by jasonb5** [comment]
I haven't yet, it's next up.

TODO
- [ ] Build and test on Nimbus
- [ ] Correct workflow triggers; should always build for PR's but only push when a new tag is created

**Comment by sashakames** [comment]
This failed test might be an intermittent issue

**Comment by downiec** [comment]
> This failed test might be an intermittent issue

Still trying to figure out why this fails on github but passes locally...

**Review by downiec — APPROVED** [review]
Tried testing this locally and looks like everything works fine. I think we can merge with v1.1.0 and then I'll figure out why the globus test is failing

**Pull request merged**
