### PR TITLE
Fixes local container

### PR DESCRIPTION
**Pull request by jasonb5**
## Description

This PR updates the local container to utilize the production entrypoint. This solves three issues; the first is HTML not rendering in the news widget, the second is correctly rendering the `index.html` and `runtime_env.js`, and lastly fixing the `runtime_env.js` being written to the correct directory for local development.

Note that the `index.html` must continue to use `$VAR` rather than `%VAR%`. This enables runtime configuration, if `%VAR%` is used then the build process will substitute the values breaking runtime configuration.

Fixes # (issue)
#613 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [ ] Local Pre-commit Checks
- [ ] CI/CD Build

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] If applicable - I have commented my code, particularly in hard-to-understand areas
- [ ] If applicable - I have made corresponding changes to the documentation
- [ ] If applicable - I have added tests that prove my fix is effective or that my feature works
- [ ] If applicable - New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by downiec — APPROVED** [review]

**Comment by sashakames** [comment]
Is this another "intermittent" error?
```
       944 |
      945 |     // GitHub icon renders
    > 946 |     const metagridSupportHeader = findByText(' MetaGrid Support');
          |                                   ^
      947 |     expect(metagridSupportHeader).toBeTruthy();
```

**Comment by jasonb5** [comment]
There might be an issue specific to the Helm chart, looking into it now.

**Comment by jasonb5** [comment]
Confirmed need to make another change to this PR.

**Comment by jasonb5** [comment]
@sashakames @downiec Figured out the failing test, I forgot that the `index.html` needs to be manually rendered in the frontend testing workflow.

**Pull request merged**
