### PR TITLE
V1.1.0

### PR DESCRIPTION
**Pull request by downiec**
## Description

This is the new update branch for Metagrid

Fixes # 

## How Has This Been Tested?

- [ ] Local Pre-commit Checks
- [ ] CI/CD Build

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] If applicable - I have commented my code, particularly in hard-to-understand areas
- [ ] If applicable - I have made corresponding changes to the documentation
- [ ] If applicable - I have added tests that prove my fix is effective or that my feature works
- [ ] If applicable - New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sashakames** [comment]
## Plan to include the following:

- [ ] endpoint_mapping
- [ ] Jason's changes to support Helm Charts / K8S
- [ ] UUID error codes for Transfer failures
- [ ] Copy Facet list
- [ ] Open project on click ?
- [ ] Single Dataset transfer
- [ ] Managed Mapped endpoints
- [ ] Any minor package updates ?
- [ ] Developer / Operator (not user) documentation updates
- [ ] Anything else ?
For sure a major release!

**Comment by sashakames** [comment]
Screenshot 2024-02-12 at 10 55 41 AM

**Comment by sashakames** [comment]
I recall we passed this, what gives????

**Comment by downiec** [comment]
Not sure why it's failing now, will have to look into it.

**Comment by jasonb5** [comment]
@downiec Can we get pre-commit to run on branches targeting vX.X.X branches? I realized that last formatting issue was from my branch.

**Comment by downiec** [comment]
> @downiec Can we get pre-commit to run on branches targeting vX.X.X branches? I realized that last formatting issue was from my branch.

Yeah, I think we would need to adjust the pre-commit.yml file to do that

**Comment by sashakames** [comment]
I think we will call this branch feature complete.  Once tests pass for the final PR, we can put this under review and plan to merge...

**Comment by sashakames** [comment]
Should we close this and rename to `v1.1.1` ?

**Pull request closed without merging**
